name: usplat4d
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - python=3.10.19
  - pip=22.3.1
  - tqdm=4.65.0
  - Pillow=9.4.0
  - numpy=1.26.4
  - pip:
    - open3d==0.16.0
